# https://gohugo.io/getting-started/configuration/

title: Michael Forster
baseURL: "https://michael.forster.pro/"

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

permalinks:
  categories: "/category/:slug/"
  posts: "/post/:slugorfilename/"
  publications: "/publication/:slugorfilename/"
  tags: "/tag/:slug/"

taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags

imaging:
  resampleFilter: lanczos
  quality: 95

markup:
  _merge: deep

security:
  _merge: deep
