# https://wowchemy.com/docs/getting-started/customization/

appearance:
  theme_day: minimal
  theme_night: minimal

features:
  syntax_highlighter:
    theme_light: dracula
    theme_dark: dracula

locale:
  date_format: 2006-01-02
  time_format: 15:04

publications:
  citation_style: mla

i_am_a_sponsor: true
