# https://wowchemy.com/docs/getting-started/customization/

appearance:
  theme_day: minimal
  theme_night: minimal
  font: mforster

features:
  syntax_highlighter:
    theme_light: base16-mike
    theme_dark: base16-mike
  comment:
    provider: mastodon

locale:
  date_format: 2006-01-02
  time_format: 15:04

publications:
  citation_style: mla

i_am_a_sponsor: true
